version: '2'
services:

  redis:
    image: redis
    ports:
      - 6379

  db:
    build: db/
    ports:
      - 3306
    environment:
      exchange_name: Coinapult Exchange
    volumes:
      - ./var/mysql:/var/lib/mysql

  wallet:
    image: ensocoin
    container_name: ensocoind
    command: ensocoind -testnet
    ports:
      - 17992:17992
    environment:
      testnet: 1
    volumes:
      - /media/DATA/Ensocoin:/data
      - ./var/wallet/notify:/notify

  cron:
    image: {{IMAGE}}-cron:{{VERSION}}
    links:
      - db
    volumes:
      - ./var/wallet/notify:/notify

  cryptocap:
    image: {{IMAGE}}-cryptocap:{{VERSION}}
    command: npm run dev
    links:
      - db
    environment:
      dbhost: db
      dbname: wlox
      dbuser: wlox
      dbpass: wlox

  api:
    image: {{IMAGE}}-api:{{VERSION}}
    links:
      - db
      - wallet
    ports:
      - 80

  auth:
    image: {{IMAGE}}-auth:{{VERSION}}
    links:
      - db
    ports:
      - 80

  frontend:
    image: {{IMAGE}}-frontend:{{VERSION}}
    links:
      - api
      - auth
      - redis
    ports:
      - {{FRONTEND_PORT}}
    volumes:
      - ./frontend/htdocs:/var/www/html
      - ./frontend/lib:/var/www/lib
      - ./frontend/public_api:/var/www/public_api

  backstage2:
    image: {{IMAGE}}-backstage2:{{VERSION}}
    links:
      - db
    ports:
      - {{ADMIN_PORT}}

networks:
  default:
    external:
      name: ensocoin
